server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_cart_db
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  cloud:
    config:
      fail-fast: true
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000