spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000